sudo: false
matrix:
  include:
    - language: python
      python: 2.7
      env: TOXENV=py27
    - language: python
      python: 3.5
      env: TOXENV=py35
    - language: python
      python: 3.6
      env: TOXENV=py36
    - language: python
      python: pypy
      env: TOXENV=pypy
    - language: python
      python: 2.7
      env: TOXENV=py27-benchmark
    - language: python
      python: 3.6
      env: TOXENV=py36-benchmark
    - language: python
      python: pypy
      env: TOXENV=pypy-benchmark
    - language: rust
      rust: stable
    - language: rust
      rust: beta
    - language: rust
      rust: nightly
install:
  - if [[ -n "$TOXENV" ]] ; then pip install tox; fi
script:
  - if [[ -n "$TOXENV" ]] ; then tox; fi
  - if [[ -z "$TOXENV" ]] ; then cargo build --verbose --all ; fi
  - if [[ -z "$TOXENV" ]] ; then cargo test --verbose --all ; fi
  - if [[ -z "$TOXENV" ]] && [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo bench --verbose --all ; fi
